---@param theme GrubboxTheme
---@param colors GrubboxColors
return function(theme, colors)
  vim.g.terminal_color_0  = theme.bg1[1]
  vim.g.terminal_color_8  = theme.bg0[1]
  vim.g.terminal_color_1  = theme.red[1]
  vim.g.terminal_color_9  = colors.neutral.red[1]
  vim.g.terminal_color_2 = theme.green[1]
  vim.g.terminal_color_10  = colors.neutral.green[1]
  vim.g.terminal_color_3 = theme.yellow[1]
  vim.g.terminal_color_11  = colors.neutral.yellow[1]
  vim.g.terminal_color_4 = theme.blue[1]
  vim.g.terminal_color_12  = colors.neutral.blue[1]
  vim.g.terminal_color_5 = theme.purple[1]
  vim.g.terminal_color_13  = colors.neutral.purple[1]
  vim.g.terminal_color_6 = theme.aqua[1]
  vim.g.terminal_color_14  = colors.neutral.aqua[1]
  vim.g.terminal_color_7 = theme.bg3[1]
  vim.g.terminal_color_15  = theme.bg4[1]
end
